# Generated by Django 4.1.3 on 2022-11-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='juegos',
            name='publicación',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='estreno',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='estreno',
        ),
        migrations.RemoveField(
            model_name='series',
            name='estreno',
        ),
    ]
