# Generated by Django 4.1.3 on 2022-12-09 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0004_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
