# Generated by Django 4.1.3 on 2022-12-09 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0005_libros_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='likes',
            field=models.ManyToManyField(related_name='likes_juegos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='likes',
            field=models.ManyToManyField(related_name='likes_peliculas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='series',
            name='likes',
            field=models.ManyToManyField(related_name='likes_series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libros',
            name='likes',
            field=models.ManyToManyField(related_name='likes_libros', to=settings.AUTH_USER_MODEL),
        ),
    ]
