# Generated by Django 4.1.3 on 2022-12-10 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_juegos_likes_peliculas_likes_series_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='likes',
        ),
    ]
