# Generated by Django 4.1.3 on 2022-12-13 01:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0007_remove_libros_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='likes',
            field=models.ManyToManyField(related_name='libros_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='likes',
            field=models.ManyToManyField(related_name='juegos_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='likes',
            field=models.ManyToManyField(related_name='peliculas_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='series',
            name='likes',
            field=models.ManyToManyField(related_name='series_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
