# Generated by Django 4.1.3 on 2022-12-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_libros_likes_alter_juegos_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juegos',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='series',
            name='likes',
        ),
    ]
